"""
AttributeError means there is a reference to something that does not exist

you can create variables, functions, classes, attributes and methods to solve AttributeError
"""
import unittest
import module


class TestAttributeError(unittest.TestCase):
    def test_defining_variables_to_solve_attribute_errors(self):
        self.assertIsNone(module.attribute_0)
        self.assertIsNone(module.attribute_1)
        self.assertIsNone(module.attribute_2)
        self.assertIsNone(module.attribute_3)
        self.assertIsNone(module.attribute_4)
        self.assertIsNone(module.attribute_5)
        self.assertIsNone(module.attribute_6)
        self.assertIsNone(module.attribute_7)
        self.assertIsNone(module.attribute_8)
        self.assertIsNone(module.attribute_9)
        self.assertIsNone(module.attribute_10)
        self.assertIsNone(module.attribute_11)
        self.assertIsNone(module.attribute_12)
        self.assertIsNone(module.attribute_13)
        self.assertIsNone(module.attribute_14)
        self.assertIsNone(module.attribute_15)
        self.assertIsNone(module.attribute_16)
        self.assertIsNone(module.attribute_17)
        self.assertIsNone(module.attribute_18)
        self.assertIsNone(module.attribute_19)
        self.assertIsNone(module.attribute_20)
        self.assertIsNone(module.attribute_21)
        self.assertIsNone(module.attribute_22)
        self.assertIsNone(module.attribute_23)
        self.assertIsNone(module.attribute_24)
        self.assertIsNone(module.attribute_25)
        self.assertIsNone(module.attribute_26)
        self.assertIsNone(module.attribute_27)
        self.assertIsNone(module.attribute_28)
        self.assertIsNone(module.attribute_29)
        self.assertIsNone(module.attribute_30)
        self.assertIsNone(module.attribute_34)
        self.assertIsNone(module.attribute_32)
        self.assertIsNone(module.attribute_33)
        self.assertIsNone(module.attribute_34)
        self.assertIsNone(module.attribute_35)
        self.assertIsNone(module.attribute_36)
        self.assertIsNone(module.attribute_37)
        self.assertIsNone(module.attribute_38)
        self.assertIsNone(module.attribute_39)
        self.assertIsNone(module.attribute_40)
        self.assertIsNone(module.attribute_41)
        self.assertIsNone(module.attribute_42)
        self.assertIsNone(module.attribute_43)
        self.assertIsNone(module.attribute_44)
        self.assertIsNone(module.attribute_45)
        self.assertIsNone(module.attribute_46)
        self.assertIsNone(module.attribute_47)
        self.assertIsNone(module.attribute_48)
        self.assertIsNone(module.attribute_49)
        self.assertIsNone(module.attribute_50)
        self.assertIsNone(module.attribute_51)
        self.assertIsNone(module.attribute_52)
        self.assertIsNone(module.attribute_53)
        self.assertIsNone(module.attribute_54)
        self.assertIsNone(module.attribute_55)
        self.assertIsNone(module.attribute_56)
        self.assertIsNone(module.attribute_57)
        self.assertIsNone(module.attribute_58)
        self.assertIsNone(module.attribute_59)
        self.assertIsNone(module.attribute_60)
        self.assertIsNone(module.attribute_61)
        self.assertIsNone(module.attribute_62)
        self.assertIsNone(module.attribute_63)
        self.assertIsNone(module.attribute_64)
        self.assertIsNone(module.attribute_65)
        self.assertIsNone(module.attribute_66)
        self.assertIsNone(module.attribute_67)
        self.assertIsNone(module.attribute_68)
        self.assertIsNone(module.attribute_69)
        self.assertIsNone(module.attribute_70)
        self.assertIsNone(module.attribute_71)
        self.assertIsNone(module.attribute_72)
        self.assertIsNone(module.attribute_73)
        self.assertIsNone(module.attribute_74)
        self.assertIsNone(module.attribute_75)
        self.assertIsNone(module.attribute_76)
        self.assertIsNone(module.attribute_77)
        self.assertIsNone(module.attribute_78)
        self.assertIsNone(module.attribute_79)
        self.assertIsNone(module.attribute_80)
        self.assertIsNone(module.attribute_81)
        self.assertIsNone(module.attribute_82)
        self.assertIsNone(module.attribute_83)
        self.assertIsNone(module.attribute_84)
        self.assertIsNone(module.attribute_85)
        self.assertIsNone(module.attribute_86)
        self.assertIsNone(module.attribute_87)
        self.assertIsNone(module.attribute_88)
        self.assertIsNone(module.attribute_89)
        self.assertIsNone(module.attribute_90)
        self.assertIsNone(module.attribute_91)
        self.assertIsNone(module.attribute_92)
        self.assertIsNone(module.attribute_93)
        self.assertIsNone(module.attribute_94)
        self.assertIsNone(module.attribute_95)
        self.assertIsNone(module.attribute_96)
        self.assertIsNone(module.attribute_97)
        self.assertIsNone(module.attribute_98)
        self.assertIsNone(module.attribute_99)
        self.assertFalse(module.false)
        self.assertTrue(module.true)

    def test_defining_functions_to_solve_attribute_errors(self):
        self.assertIsNone(module.function_0())
        self.assertIsNone(module.function_1())
        self.assertIsNone(module.function_2())
        self.assertIsNone(module.function_3())
        self.assertIsNone(module.function_4())
        self.assertIsNone(module.function_5())
        self.assertIsNone(module.function_6())
        self.assertIsNone(module.function_7())
        self.assertIsNone(module.function_8())
        self.assertIsNone(module.function_9())
        self.assertIsNone(module.function_10())
        self.assertIsNone(module.function_11())
        self.assertIsNone(module.function_12())
        self.assertIsNone(module.function_13())
        self.assertIsNone(module.function_14())
        self.assertIsNone(module.function_15())
        self.assertIsNone(module.function_16())
        self.assertIsNone(module.function_17())
        self.assertIsNone(module.function_18())
        self.assertIsNone(module.function_19())
        self.assertIsNone(module.function_20())
        self.assertIsNone(module.function_21())
        self.assertIsNone(module.function_22())
        self.assertIsNone(module.function_23())
        self.assertIsNone(module.function_24())
        self.assertIsNone(module.function_25())
        self.assertIsNone(module.function_26())
        self.assertIsNone(module.function_27())
        self.assertIsNone(module.function_28())
        self.assertIsNone(module.function_29())
        self.assertIsNone(module.function_30())
        self.assertIsNone(module.function_34())
        self.assertIsNone(module.function_32())
        self.assertIsNone(module.function_33())
        self.assertIsNone(module.function_34())
        self.assertIsNone(module.function_35())
        self.assertIsNone(module.function_36())
        self.assertIsNone(module.function_37())
        self.assertIsNone(module.function_38())
        self.assertIsNone(module.function_39())
        self.assertIsNone(module.function_40())
        self.assertIsNone(module.function_41())
        self.assertIsNone(module.function_42())
        self.assertIsNone(module.function_43())
        self.assertIsNone(module.function_44())
        self.assertIsNone(module.function_45())
        self.assertIsNone(module.function_46())
        self.assertIsNone(module.function_47())
        self.assertIsNone(module.function_48())
        self.assertIsNone(module.function_49())
        self.assertIsNone(module.function_50())
        self.assertIsNone(module.function_51())
        self.assertIsNone(module.function_52())
        self.assertIsNone(module.function_53())
        self.assertIsNone(module.function_54())
        self.assertIsNone(module.function_55())
        self.assertIsNone(module.function_56())
        self.assertIsNone(module.function_57())
        self.assertIsNone(module.function_58())
        self.assertIsNone(module.function_59())
        self.assertIsNone(module.function_60())
        self.assertIsNone(module.function_61())
        self.assertIsNone(module.function_62())
        self.assertIsNone(module.function_63())
        self.assertIsNone(module.function_64())
        self.assertIsNone(module.function_65())
        self.assertIsNone(module.function_66())
        self.assertIsNone(module.function_67())
        self.assertIsNone(module.function_68())
        self.assertIsNone(module.function_69())
        self.assertIsNone(module.function_70())
        self.assertIsNone(module.function_71())
        self.assertIsNone(module.function_72())
        self.assertIsNone(module.function_73())
        self.assertIsNone(module.function_74())
        self.assertIsNone(module.function_75())
        self.assertIsNone(module.function_76())
        self.assertIsNone(module.function_77())
        self.assertIsNone(module.function_78())
        self.assertIsNone(module.function_79())
        self.assertIsNone(module.function_80())
        self.assertIsNone(module.function_81())
        self.assertIsNone(module.function_82())
        self.assertIsNone(module.function_83())
        self.assertIsNone(module.function_84())
        self.assertIsNone(module.function_85())
        self.assertIsNone(module.function_86())
        self.assertIsNone(module.function_87())
        self.assertIsNone(module.function_88())
        self.assertIsNone(module.function_89())
        self.assertIsNone(module.function_90())
        self.assertIsNone(module.function_91())
        self.assertIsNone(module.function_92())
        self.assertIsNone(module.function_93())
        self.assertIsNone(module.function_94())
        self.assertIsNone(module.function_95())
        self.assertIsNone(module.function_96())
        self.assertIsNone(module.function_97())
        self.assertIsNone(module.function_98())
        self.assertIsNone(module.function_99())

    def test_defining_classes_to_solve_attribute_errors(self):
        self.assertIsInstance(module.Class0(), object)
        self.assertIsInstance(module.Class1(), object)
        self.assertIsInstance(module.Class2(), object)
        self.assertIsInstance(module.Class3(), object)
        self.assertIsInstance(module.Class4(), object)
        self.assertIsInstance(module.Class5(), object)
        self.assertIsInstance(module.Class6(), object)
        self.assertIsInstance(module.Class7(), object)
        self.assertIsInstance(module.Class8(), object)
        self.assertIsInstance(module.Class9(), object)
        self.assertIsInstance(module.Class10(), object)
        self.assertIsInstance(module.Class11(), object)
        self.assertIsInstance(module.Class12(), object)
        self.assertIsInstance(module.Class13(), object)
        self.assertIsInstance(module.Class14(), object)
        self.assertIsInstance(module.Class15(), object)
        self.assertIsInstance(module.Class16(), object)
        self.assertIsInstance(module.Class17(), object)
        self.assertIsInstance(module.Class18(), object)
        self.assertIsInstance(module.Class19(), object)
        self.assertIsInstance(module.Class20(), object)
        self.assertIsInstance(module.Class21(), object)
        self.assertIsInstance(module.Class22(), object)
        self.assertIsInstance(module.Class23(), object)
        self.assertIsInstance(module.Class24(), object)
        self.assertIsInstance(module.Class25(), object)
        self.assertIsInstance(module.Class26(), object)
        self.assertIsInstance(module.Class27(), object)
        self.assertIsInstance(module.Class28(), object)
        self.assertIsInstance(module.Class29(), object)
        self.assertIsInstance(module.Class30(), object)
        self.assertIsInstance(module.Class34(), object)
        self.assertIsInstance(module.Class32(), object)
        self.assertIsInstance(module.Class33(), object)
        self.assertIsInstance(module.Class34(), object)
        self.assertIsInstance(module.Class35(), object)
        self.assertIsInstance(module.Class36(), object)
        self.assertIsInstance(module.Class37(), object)
        self.assertIsInstance(module.Class38(), object)
        self.assertIsInstance(module.Class39(), object)
        self.assertIsInstance(module.Class40(), object)
        self.assertIsInstance(module.Class41(), object)
        self.assertIsInstance(module.Class42(), object)
        self.assertIsInstance(module.Class43(), object)
        self.assertIsInstance(module.Class44(), object)
        self.assertIsInstance(module.Class45(), object)
        self.assertIsInstance(module.Class46(), object)
        self.assertIsInstance(module.Class47(), object)
        self.assertIsInstance(module.Class48(), object)
        self.assertIsInstance(module.Class49(), object)
        self.assertIsInstance(module.Class50(), object)
        self.assertIsInstance(module.Class51(), object)
        self.assertIsInstance(module.Class52(), object)
        self.assertIsInstance(module.Class53(), object)
        self.assertIsInstance(module.Class54(), object)
        self.assertIsInstance(module.Class55(), object)
        self.assertIsInstance(module.Class56(), object)
        self.assertIsInstance(module.Class57(), object)
        self.assertIsInstance(module.Class58(), object)
        self.assertIsInstance(module.Class59(), object)
        self.assertIsInstance(module.Class60(), object)
        self.assertIsInstance(module.Class61(), object)
        self.assertIsInstance(module.Class62(), object)
        self.assertIsInstance(module.Class63(), object)
        self.assertIsInstance(module.Class64(), object)
        self.assertIsInstance(module.Class65(), object)
        self.assertIsInstance(module.Class66(), object)
        self.assertIsInstance(module.Class67(), object)
        self.assertIsInstance(module.Class68(), object)
        self.assertIsInstance(module.Class69(), object)
        self.assertIsInstance(module.Class70(), object)
        self.assertIsInstance(module.Class71(), object)
        self.assertIsInstance(module.Class72(), object)
        self.assertIsInstance(module.Class73(), object)
        self.assertIsInstance(module.Class74(), object)
        self.assertIsInstance(module.Class75(), object)
        self.assertIsInstance(module.Class76(), object)
        self.assertIsInstance(module.Class77(), object)
        self.assertIsInstance(module.Class78(), object)
        self.assertIsInstance(module.Class79(), object)
        self.assertIsInstance(module.Class80(), object)
        self.assertIsInstance(module.Class81(), object)
        self.assertIsInstance(module.Class82(), object)
        self.assertIsInstance(module.Class83(), object)
        self.assertIsInstance(module.Class84(), object)
        self.assertIsInstance(module.Class85(), object)
        self.assertIsInstance(module.Class86(), object)
        self.assertIsInstance(module.Class87(), object)
        self.assertIsInstance(module.Class88(), object)
        self.assertIsInstance(module.Class89(), object)
        self.assertIsInstance(module.Class90(), object)
        self.assertIsInstance(module.Class91(), object)
        self.assertIsInstance(module.Class92(), object)
        self.assertIsInstance(module.Class93(), object)
        self.assertIsInstance(module.Class94(), object)
        self.assertIsInstance(module.Class95(), object)
        self.assertIsInstance(module.Class96(), object)
        self.assertIsInstance(module.Class97(), object)
        self.assertIsInstance(module.Class98(), object)
        self.assertIsInstance(module.Class99(), object)

    def test_defining_attributes_in_classes_to_solve_attribute_errors(self):
        self.assertIsNone(module.Class.attribute_0)
        self.assertIsNone(module.Class.attribute_1)
        self.assertIsNone(module.Class.attribute_2)
        self.assertIsNone(module.Class.attribute_3)
        self.assertIsNone(module.Class.attribute_4)
        self.assertIsNone(module.Class.attribute_5)
        self.assertIsNone(module.Class.attribute_6)
        self.assertIsNone(module.Class.attribute_7)
        self.assertIsNone(module.Class.attribute_8)
        self.assertIsNone(module.Class.attribute_9)
        self.assertIsNone(module.Class.attribute_10)
        self.assertIsNone(module.Class.attribute_11)
        self.assertIsNone(module.Class.attribute_12)
        self.assertIsNone(module.Class.attribute_13)
        self.assertIsNone(module.Class.attribute_14)
        self.assertIsNone(module.Class.attribute_15)
        self.assertIsNone(module.Class.attribute_16)
        self.assertIsNone(module.Class.attribute_17)
        self.assertIsNone(module.Class.attribute_18)
        self.assertIsNone(module.Class.attribute_19)
        self.assertIsNone(module.Class.attribute_20)
        self.assertIsNone(module.Class.attribute_21)
        self.assertIsNone(module.Class.attribute_22)
        self.assertIsNone(module.Class.attribute_23)
        self.assertIsNone(module.Class.attribute_24)
        self.assertIsNone(module.Class.attribute_25)
        self.assertIsNone(module.Class.attribute_26)
        self.assertIsNone(module.Class.attribute_27)
        self.assertIsNone(module.Class.attribute_28)
        self.assertIsNone(module.Class.attribute_29)
        self.assertIsNone(module.Class.attribute_30)
        self.assertIsNone(module.Class.attribute_34)
        self.assertIsNone(module.Class.attribute_32)
        self.assertIsNone(module.Class.attribute_33)
        self.assertIsNone(module.Class.attribute_34)
        self.assertIsNone(module.Class.attribute_35)
        self.assertIsNone(module.Class.attribute_36)
        self.assertIsNone(module.Class.attribute_37)
        self.assertIsNone(module.Class.attribute_38)
        self.assertIsNone(module.Class.attribute_39)
        self.assertIsNone(module.Class.attribute_40)
        self.assertIsNone(module.Class.attribute_41)
        self.assertIsNone(module.Class.attribute_42)
        self.assertIsNone(module.Class.attribute_43)
        self.assertIsNone(module.Class.attribute_44)
        self.assertIsNone(module.Class.attribute_45)
        self.assertIsNone(module.Class.attribute_46)
        self.assertIsNone(module.Class.attribute_47)
        self.assertIsNone(module.Class.attribute_48)
        self.assertIsNone(module.Class.attribute_49)
        self.assertIsNone(module.Class.attribute_50)
        self.assertIsNone(module.Class.attribute_51)
        self.assertIsNone(module.Class.attribute_52)
        self.assertIsNone(module.Class.attribute_53)
        self.assertIsNone(module.Class.attribute_54)
        self.assertIsNone(module.Class.attribute_55)
        self.assertIsNone(module.Class.attribute_56)
        self.assertIsNone(module.Class.attribute_57)
        self.assertIsNone(module.Class.attribute_58)
        self.assertIsNone(module.Class.attribute_59)
        self.assertIsNone(module.Class.attribute_60)
        self.assertIsNone(module.Class.attribute_61)
        self.assertIsNone(module.Class.attribute_62)
        self.assertIsNone(module.Class.attribute_63)
        self.assertIsNone(module.Class.attribute_64)
        self.assertIsNone(module.Class.attribute_65)
        self.assertIsNone(module.Class.attribute_66)
        self.assertIsNone(module.Class.attribute_67)
        self.assertIsNone(module.Class.attribute_68)
        self.assertIsNone(module.Class.attribute_69)
        self.assertIsNone(module.Class.attribute_70)
        self.assertIsNone(module.Class.attribute_71)
        self.assertIsNone(module.Class.attribute_72)
        self.assertIsNone(module.Class.attribute_73)
        self.assertIsNone(module.Class.attribute_74)
        self.assertIsNone(module.Class.attribute_75)
        self.assertIsNone(module.Class.attribute_76)
        self.assertIsNone(module.Class.attribute_77)
        self.assertIsNone(module.Class.attribute_78)
        self.assertIsNone(module.Class.attribute_79)
        self.assertIsNone(module.Class.attribute_80)
        self.assertIsNone(module.Class.attribute_81)
        self.assertIsNone(module.Class.attribute_82)
        self.assertIsNone(module.Class.attribute_83)
        self.assertIsNone(module.Class.attribute_84)
        self.assertIsNone(module.Class.attribute_85)
        self.assertIsNone(module.Class.attribute_86)
        self.assertIsNone(module.Class.attribute_87)
        self.assertIsNone(module.Class.attribute_88)
        self.assertIsNone(module.Class.attribute_89)
        self.assertIsNone(module.Class.attribute_90)
        self.assertIsNone(module.Class.attribute_91)
        self.assertIsNone(module.Class.attribute_92)
        self.assertIsNone(module.Class.attribute_93)
        self.assertIsNone(module.Class.attribute_94)
        self.assertIsNone(module.Class.attribute_95)
        self.assertIsNone(module.Class.attribute_96)
        self.assertIsNone(module.Class.attribute_97)
        self.assertIsNone(module.Class.attribute_98)
        self.assertIsNone(module.Class.attribute_99)

    def test_defining_functions_in_classes_to_solve_attribute_errors(self):
        self.assertIsNone(module.Class.method_0())
        self.assertIsNone(module.Class.method_1())
        self.assertIsNone(module.Class.method_2())
        self.assertIsNone(module.Class.method_3())
        self.assertIsNone(module.Class.method_4())
        self.assertIsNone(module.Class.method_5())
        self.assertIsNone(module.Class.method_6())
        self.assertIsNone(module.Class.method_7())
        self.assertIsNone(module.Class.method_8())
        self.assertIsNone(module.Class.method_9())
        self.assertIsNone(module.Class.method_10())
        self.assertIsNone(module.Class.method_11())
        self.assertIsNone(module.Class.method_12())
        self.assertIsNone(module.Class.method_13())
        self.assertIsNone(module.Class.method_14())
        self.assertIsNone(module.Class.method_15())
        self.assertIsNone(module.Class.method_16())
        self.assertIsNone(module.Class.method_17())
        self.assertIsNone(module.Class.method_18())
        self.assertIsNone(module.Class.method_19())
        self.assertIsNone(module.Class.method_20())
        self.assertIsNone(module.Class.method_21())
        self.assertIsNone(module.Class.method_22())
        self.assertIsNone(module.Class.method_23())
        self.assertIsNone(module.Class.method_24())
        self.assertIsNone(module.Class.method_25())
        self.assertIsNone(module.Class.method_26())
        self.assertIsNone(module.Class.method_27())
        self.assertIsNone(module.Class.method_28())
        self.assertIsNone(module.Class.method_29())
        self.assertIsNone(module.Class.method_30())
        self.assertIsNone(module.Class.method_34())
        self.assertIsNone(module.Class.method_32())
        self.assertIsNone(module.Class.method_33())
        self.assertIsNone(module.Class.method_34())
        self.assertIsNone(module.Class.method_35())
        self.assertIsNone(module.Class.method_36())
        self.assertIsNone(module.Class.method_37())
        self.assertIsNone(module.Class.method_38())
        self.assertIsNone(module.Class.method_39())
        self.assertIsNone(module.Class.method_40())
        self.assertIsNone(module.Class.method_41())
        self.assertIsNone(module.Class.method_42())
        self.assertIsNone(module.Class.method_43())
        self.assertIsNone(module.Class.method_44())
        self.assertIsNone(module.Class.method_45())
        self.assertIsNone(module.Class.method_46())
        self.assertIsNone(module.Class.method_47())
        self.assertIsNone(module.Class.method_48())
        self.assertIsNone(module.Class.method_49())
        self.assertIsNone(module.Class.method_50())
        self.assertIsNone(module.Class.method_51())
        self.assertIsNone(module.Class.method_52())
        self.assertIsNone(module.Class.method_53())
        self.assertIsNone(module.Class.method_54())
        self.assertIsNone(module.Class.method_55())
        self.assertIsNone(module.Class.method_56())
        self.assertIsNone(module.Class.method_57())
        self.assertIsNone(module.Class.method_58())
        self.assertIsNone(module.Class.method_59())
        self.assertIsNone(module.Class.method_60())
        self.assertIsNone(module.Class.method_61())
        self.assertIsNone(module.Class.method_62())
        self.assertIsNone(module.Class.method_63())
        self.assertIsNone(module.Class.method_64())
        self.assertIsNone(module.Class.method_65())
        self.assertIsNone(module.Class.method_66())
        self.assertIsNone(module.Class.method_67())
        self.assertIsNone(module.Class.method_68())
        self.assertIsNone(module.Class.method_69())
        self.assertIsNone(module.Class.method_70())
        self.assertIsNone(module.Class.method_71())
        self.assertIsNone(module.Class.method_72())
        self.assertIsNone(module.Class.method_73())
        self.assertIsNone(module.Class.method_74())
        self.assertIsNone(module.Class.method_75())
        self.assertIsNone(module.Class.method_76())
        self.assertIsNone(module.Class.method_77())
        self.assertIsNone(module.Class.method_78())
        self.assertIsNone(module.Class.method_79())
        self.assertIsNone(module.Class.method_80())
        self.assertIsNone(module.Class.method_81())
        self.assertIsNone(module.Class.method_82())
        self.assertIsNone(module.Class.method_83())
        self.assertIsNone(module.Class.method_84())
        self.assertIsNone(module.Class.method_85())
        self.assertIsNone(module.Class.method_86())
        self.assertIsNone(module.Class.method_87())
        self.assertIsNone(module.Class.method_88())
        self.assertIsNone(module.Class.method_89())
        self.assertIsNone(module.Class.method_90())
        self.assertIsNone(module.Class.method_91())
        self.assertIsNone(module.Class.method_92())
        self.assertIsNone(module.Class.method_93())
        self.assertIsNone(module.Class.method_94())
        self.assertIsNone(module.Class.method_95())
        self.assertIsNone(module.Class.method_96())
        self.assertIsNone(module.Class.method_97())
        self.assertIsNone(module.Class.method_98())
        self.assertIsNone(module.Class.method_99())