"""
AttributeError means there is a reference to something that does not exist

you can create variables, functions, classes, attributes and methods to solve AttributeError
"""
import unittest
import module


class TestAttributeError(unittest.TestCase):
    def test_defining_variables_to_solve_attribute_errors(self):
        self.assertIsNone(module.variable_a)
        self.assertIsNone(module.variable_b)
        self.assertIsNone(module.variable_c)
        self.assertIsNone(module.variable_d)
        self.assertIsNone(module.variable_e)
        self.assertIsNone(module.variable_f)
        self.assertIsNone(module.variable_g)
        self.assertIsNone(module.variable_h)
        self.assertIsNone(module.variable_i)
        self.assertIsNone(module.variable_j)
        self.assertIsNone(module.variable_k)
        self.assertIsNone(module.variable_l)
        self.assertIsNone(module.variable_m)
        self.assertIsNone(module.variable_n)
        self.assertIsNone(module.variable_o)
        self.assertIsNone(module.variable_p)
        self.assertIsNone(module.variable_q)
        self.assertIsNone(module.variable_r)
        self.assertIsNone(module.variable_s)
        self.assertIsNone(module.variable_t)
        self.assertIsNone(module.variable_u)
        self.assertIsNone(module.variable_v)
        self.assertIsNone(module.variable_w)
        self.assertIsNone(module.variable_x)
        self.assertIsNone(module.variable_y)
        self.assertIsNone(module.variable_z)

    def test_defining_functions_to_solve_attribute_errors(self):
        self.assertIsNone(module.function_a())
        self.assertIsNone(module.function_b())
        self.assertIsNone(module.function_c())
        self.assertIsNone(module.function_d())
        self.assertIsNone(module.function_e())
        self.assertIsNone(module.function_f())
        self.assertIsNone(module.function_g())
        self.assertIsNone(module.function_h())
        self.assertIsNone(module.function_i())
        self.assertIsNone(module.function_j())
        self.assertIsNone(module.function_k())
        self.assertIsNone(module.function_l())
        self.assertIsNone(module.function_m())
        self.assertIsNone(module.function_n())
        self.assertIsNone(module.function_o())
        self.assertIsNone(module.function_p())
        self.assertIsNone(module.function_q())
        self.assertIsNone(module.function_r())
        self.assertIsNone(module.function_s())
        self.assertIsNone(module.function_t())
        self.assertIsNone(module.function_u())
        self.assertIsNone(module.function_v())
        self.assertIsNone(module.function_w())
        self.assertIsNone(module.function_x())
        self.assertIsNone(module.function_y())
        self.assertIsNone(module.function_z())

    def test_defining_classes_to_solve_attribute_errors(self):
        self.assertIsInstance(module.ClassA(), object)
        self.assertIsInstance(module.ClassB(), object)
        self.assertIsInstance(module.ClassC(), object)
        self.assertIsInstance(module.ClassD(), object)
        self.assertIsInstance(module.ClassE(), object)
        self.assertIsInstance(module.ClassF(), object)
        self.assertIsInstance(module.ClassG(), object)
        self.assertIsInstance(module.ClassH(), object)
        self.assertIsInstance(module.ClassI(), object)
        self.assertIsInstance(module.ClassJ(), object)
        self.assertIsInstance(module.ClassK(), object)
        self.assertIsInstance(module.ClassL(), object)
        self.assertIsInstance(module.ClassM(), object)
        self.assertIsInstance(module.ClassN(), object)
        self.assertIsInstance(module.ClassO(), object)
        self.assertIsInstance(module.ClassP(), object)
        self.assertIsInstance(module.ClassQ(), object)
        self.assertIsInstance(module.ClassR(), object)
        self.assertIsInstance(module.ClassS(), object)
        self.assertIsInstance(module.ClassT(), object)
        self.assertIsInstance(module.ClassU(), object)
        self.assertIsInstance(module.ClassV(), object)
        self.assertIsInstance(module.ClassW(), object)
        self.assertIsInstance(module.ClassX(), object)
        self.assertIsInstance(module.ClassY(), object)
        self.assertIsInstance(module.ClassZ(), object)

    def test_defining_attributes_in_classes_to_solve_attribute_errors(self):
        self.assertIsNone(module.Class.attribute_a)
        self.assertIsNone(module.Class.attribute_b)
        self.assertIsNone(module.Class.attribute_c)
        self.assertIsNone(module.Class.attribute_d)
        self.assertIsNone(module.Class.attribute_e)
        self.assertIsNone(module.Class.attribute_f)
        self.assertIsNone(module.Class.attribute_g)
        self.assertIsNone(module.Class.attribute_h)
        self.assertIsNone(module.Class.attribute_i)
        self.assertIsNone(module.Class.attribute_j)
        self.assertIsNone(module.Class.attribute_k)
        self.assertIsNone(module.Class.attribute_l)
        self.assertIsNone(module.Class.attribute_m)
        self.assertIsNone(module.Class.attribute_n)
        self.assertIsNone(module.Class.attribute_o)
        self.assertIsNone(module.Class.attribute_p)
        self.assertIsNone(module.Class.attribute_q)
        self.assertIsNone(module.Class.attribute_r)
        self.assertIsNone(module.Class.attribute_s)
        self.assertIsNone(module.Class.attribute_t)
        self.assertIsNone(module.Class.attribute_u)
        self.assertIsNone(module.Class.attribute_v)
        self.assertIsNone(module.Class.attribute_w)
        self.assertIsNone(module.Class.attribute_x)
        self.assertIsNone(module.Class.attribute_y)
        self.assertIsNone(module.Class.attribute_z)

    def test_defining_functions_in_classes_to_solve_attribute_errors(self):
        self.assertIsNone(module.Class.method_a())
        self.assertIsNone(module.Class.method_b())
        self.assertIsNone(module.Class.method_c())
        self.assertIsNone(module.Class.method_d())
        self.assertIsNone(module.Class.method_e())
        self.assertIsNone(module.Class.method_f())
        self.assertIsNone(module.Class.method_g())
        self.assertIsNone(module.Class.method_h())
        self.assertIsNone(module.Class.method_i())
        self.assertIsNone(module.Class.method_j())
        self.assertIsNone(module.Class.method_k())
        self.assertIsNone(module.Class.method_l())
        self.assertIsNone(module.Class.method_m())
        self.assertIsNone(module.Class.method_n())
        self.assertIsNone(module.Class.method_o())
        self.assertIsNone(module.Class.method_p())
        self.assertIsNone(module.Class.method_q())
        self.assertIsNone(module.Class.method_r())
        self.assertIsNone(module.Class.method_s())
        self.assertIsNone(module.Class.method_t())
        self.assertIsNone(module.Class.method_u())
        self.assertIsNone(module.Class.method_v())
        self.assertIsNone(module.Class.method_w())
        self.assertIsNone(module.Class.method_x())
        self.assertIsNone(module.Class.method_y())
        self.assertIsNone(module.Class.method_z())
